In [1]:
import pandas as pd
import os

data_dir = os.path.expanduser("~/Research/Terrabyte/Hypergraph_GRAND/datasets/cora")

In [2]:
edge_list = pd.read_csv(os.path.join(data_dir, "cora.cites"), sep='\t', header=None, names=["target", "source"])
edge_list["label"] = "cities"
edge_list.shape[0]

5429

In [ ]:
df_content = pd.read_csv("/home/sajjad/src/manitoba/3.datasets/cora/cora_content.csv")

In [15]:
df_papers = pd.read_csv("/home/sajjad/src/manitoba/3.datasets/cora/cora_paper.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/home/sajjad/src/manitoba/3.datasets/cora/cora_paper.csv'

In [3]:
edge_list.head()

   target   source   label
0      35     1033  cities
1      35   103482  cities
2      35   103515  cities
3      35  1050679  cities
4      35  1103960  cities

In [ ]:
df_content.head()

   paper_id word_cited_id
0        35       word100
1        35      word1152
2        35      word1175
3        35      word1228
4        35      word1248

In [ ]:
df_papers.head()

   paper_id             class_label
0        35      Genetic_Algorithms
1        40      Genetic_Algorithms
2       114  Reinforcement_Learning
3       117  Reinforcement_Learning
4       128  Reinforcement_Learning

In [ ]:
papers = len(df_papers)

In [ ]:
# Following the direction in bai2019hypergraph

In [ ]:
classifications = list(set(df_papers["class_label"]))

In [ ]:
import numpy as np

In [ ]:
H = np.zeros((papers, papers), dtype=bool)

In [ ]:
df_cites

      cited_paper_id  citing_paper_id
0                 35              887
1                 35             1033
2                 35             1688
3                 35             1956
4                 35             8865
...              ...              ...
5424          853116            19621
5425          853116           853155
5426          853118          1140289
5427          853155           853118
5428          954315          1155073

[5429 rows x 2 columns]

In [ ]:
id_lookup = {}
for i, k in enumerate(df_papers["paper_id"].to_list()):
    id_lookup[k] = i

In [ ]:
for r in df_cites.iterrows():
    a = r[1].cited_paper_id
    b = r[1].citing_paper_id
    a = id_lookup[a]
    b = id_lookup[b]
    H[a, b] = 1
    H[b, a] = 1

In [ ]:
np.save("/home/sajjad/src/manitoba/3.datasets/cora/bai_H.npy", H)

In [ ]:
word_lookup = {}
for i, k in enumerate(set(df_content["word_cited_id"].to_list())):
    word_lookup[k] = i

In [ ]:
X = np.zeros((papers, len(word_lookup)), dtype='bool')

In [ ]:
for r in df_content.iterrows():
    a = r[1].paper_id
    b = r[1].word_cited_id
    a = id_lookup[a]
    b = word_lookup[b]
    X[a, b] = 1

In [ ]:
np.save("/home/sajjad/src/manitoba/3.datasets/cora/bai_X.npy", X)

In [ ]:
classification_lookup = {}

for i, k in enumerate(set(df_papers["class_label"].to_list())):
    classification_lookup[k] = i

In [ ]:
y = np.zeros((papers, len(classification_lookup)), dtype='bool')

In [ ]:
for r in df_papers.iterrows():
    a = r[1].paper_id
    b = r[1].class_label
    a = id_lookup[a]
    b = classification_lookup[b]
    y[a,b] = 1

In [ ]:
np.save("/home/sajjad/src/manitoba/3.datasets/cora/bai_y.npy", y)

In [ ]:
y.shape

(2708, 7)

In [ ]:
classification_lookup

{'Rule_Learning': 0,
 'Genetic_Algorithms': 1,
 'Theory': 2,
 'Neural_Networks': 3,
 'Probabilistic_Methods': 4,
 'Reinforcement_Learning': 5,
 'Case_Based': 6}